### ISSUE TITLE
refactor: 프로젝트 구조를 멀티모듈 구조로 변경한다

### ISSUE THREAD

**Issue by devxb** [woowasap/ASAP#12]
## Todo
- [ ] app 모듈 : 다른 모듈들을 통합하고 애플리케이션 실행을 담당
- [ ] auth 모듈 : 인증 역할을 담당
- [ ] core 모듈 : entity, idGenerator등 모든 모듈에서 참조해야하는것들을 담당
- [ ] shop 모듈 : 상점 역할을 담당

``` mermaid
---
title: 최상위 패키지간 의존성 방향
---

flowchart LR
    
asap.app --> asap.auth 
asap.app --> asap.shop
asap.auth --> asap.core
asap.shop --> asap.core
```
