### ISSUE TITLE
feat: Entity 설계

### ISSUE THREAD

**Issue by devxb** [woowasap/ASAP#144]
## Todo
- [ ] shop 모듈 entity 설계
- [ ] order 모듈 entity 설계
- [ ] auth 모듈 entity 설계
