### ISSUE TITLE
feat: Cart 엔티티 기능 및, 레포지토리 구현

### ISSUE THREAD

**Issue by ProtoSeo** [woowasap/ASAP#146]
## 기능

Cart 엔티티 기능 및, 레포지토리 구현한다.

## Todo
- [ ] Cart Repository 구현
- [ ] cart 엔티티 기능 구현
- [ ] 인수테스트 싱크 맞추기
