### ISSUE TITLE
feat: User 엔티티 기능 및 레포지토리 구현 

### ISSUE THREAD

**Issue by grolarkim** [woowasap/ASAP#150]
## Todo
- [x] User Repository 구현
- [x] User Entity 기능 구현
- [x] 인수테스트 싱크 맞추기
