### ISSUE TITLE
chore: Logging 전략 수정

### ISSUE THREAD

**Issue by devxb** [woowasap/ASAP#236]
## Todo
- [ ] Sentry 는 Warning 만 찍는다.
- [ ] 이벤트 전부 -> Info -> log파일로 찍는다.
- [ ] BadRequest -> Info로 찍는다.
