### ISSUE TITLE
sonar cloud 세팅

### ISSUE THREAD

**Issue by devxb** [woowasap/ASAP#4]
## Todo
- [x] sonar cloud 세팅
- [x] 인수테스트 sonar CI 세팅
- [x] 단위테스트 sonar CI 세팅
