### ISSUE TITLE
feat: 도메인 및 패키지 구조 스캐폴딩

### ISSUE THREAD

**Issue by devxb** [woowasap/ASAP#8]
## Todo
- [x] shop 도메인 생성
- [x] auth 도메인 생성
- [x] 패키지 구조 생성
